export const WARDROBE_ITEM_STORAGE_VERSION = 1;

export const DEFAULT_WARDROBE_ITEMS = Object.freeze([
  {
    id: "classic",
    label: "Classica",
    description: "Visual original do personagem.",
    characterId: "all",
    slot: "preset",
    rarity: "Base",
    assetRef: "",
    presetRef: "",
    ownedByDefault: true,
    priceCoins: 0,
    priceDiamonds: 0,
    unlockLevel: 1,
    source: "default",
    accent: "from-cyan-300 via-sky-400 to-blue-500",
  },
  {
    id: "sunset",
    label: "Sunset Rider",
    description: "Paleta quente inspirada nas ilhas ao entardecer.",
    characterId: "all",
    slot: "preset",
    rarity: "Rara",
    assetRef: "",
    presetRef: "",
    ownedByDefault: false,
    priceCoins: 1400,
    priceDiamonds: 0,
    unlockLevel: 2,
    source: "store",
    accent: "from-amber-300 via-orange-400 to-rose-500",
  },
  {
    id: "midnight",
    label: "Noite Neon",
    description: "Preset visual premium preparado para loja local.",
    characterId: "all",
    slot: "preset",
    rarity: "Epica",
    assetRef: "",
    presetRef: "",
    ownedByDefault: false,
    priceCoins: 0,
    priceDiamonds: 14,
    unlockLevel: 4,
    source: "store",
    accent: "from-fuchsia-400 via-violet-500 to-indigo-600",
  },
  {
    id: "coral_wave",
    label: "Coral Wave",
    description: "Placeholder sazonal para futuras colecoes e recompensas.",
    characterId: "richard",
    slot: "preset",
    rarity: "Lendaria",
    assetRef: "",
    presetRef: "",
    ownedByDefault: false,
    priceCoins: 0,
    priceDiamonds: 18,
    unlockLevel: 8,
    source: "reward",
    accent: "from-cyan-300 via-teal-400 to-violet-500",
  },
]);

