$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$releaseRoot = Join-Path $root "deploy\release"
$frontendRelease = Join-Path $releaseRoot "frontend"
$backendRelease = Join-Path $releaseRoot "backend"
$templatesRelease = Join-Path $releaseRoot "templates"

Write-Host "Generating frontend build..."
Push-Location $root
try {
  & npm.cmd run build
} finally {
  Pop-Location
}

if (Test-Path $releaseRoot) {
  Remove-Item -Recurse -Force $releaseRoot
}

New-Item -ItemType Directory -Force -Path $frontendRelease | Out-Null
New-Item -ItemType Directory -Force -Path $backendRelease | Out-Null
New-Item -ItemType Directory -Force -Path $templatesRelease | Out-Null

Write-Host "Copying frontend artifacts..."
Copy-Item -Path (Join-Path $root "dist\*") -Destination $frontendRelease -Recurse -Force

Write-Host "Copying backend runtime files..."
Copy-Item -Path (Join-Path $root "backend\src") -Destination $backendRelease -Recurse -Force
Copy-Item -Path (Join-Path $root "backend\package.json") -Destination $backendRelease -Force
Copy-Item -Path (Join-Path $root "backend\package-lock.json") -Destination $backendRelease -Force

if (Test-Path (Join-Path $root ".env.example")) {
  Copy-Item -Path (Join-Path $root ".env.example") -Destination (Join-Path $templatesRelease "frontend.env.example") -Force
}

if (Test-Path (Join-Path $root "backend\.env.example")) {
  Copy-Item -Path (Join-Path $root "backend\.env.example") -Destination (Join-Path $templatesRelease "backend.env.example") -Force
}

$summary = @"
Release generated at: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

Contents:
- frontend\: static files generated by Vite
- backend\: Node runtime source + package manifests
- templates\: example env files for production setup

Do not upload from this release:
- .env files with secrets
- node_modules
- postgres/redis data
- backend/uploads
- backend/private_uploads
"@

Set-Content -Path (Join-Path $releaseRoot "README.txt") -Value $summary -Encoding UTF8

Write-Host "Release ready at $releaseRoot"
